-- DungeonRares.lua
local _, addon = ...
addon.DungeonRares = {
    [1] = {
        { id = 1119, name = [[Hammerspine]] },
        { id = 1130, name = [[Bjarn]] },
        { id = 1132, name = [[Timber]] },
        { id = 1137, name = [[Edan the Howler]] },
        { id = 1260, name = [[Great Father Arctikus]] },
        { id = 1271, name = [[Old Icebeard]] },
        { id = 1388, name = [[Vagash]] },
        { id = 6209, name = [[Caverndeep Looter]] },
        { id = 6231, name = [[Techbot]] },
        { id = 8503, name = [[Gibblewilt]] },
    },
    [3] = {
        { id = 2744, name = [[Shadowforge Commander]] },
        { id = 2745, name = [[Ambassador Infernus]] },
        { id = 2749, name = [[Siege Golem]] },
        { id = 2751, name = [[War Golem]] },
        { id = 2752, name = [[Rumbler]] },
        { id = 2754, name = [[Anathemus]] },
        { id = 2850, name = [[Broken Tooth]] },
        { id = 2861, name = [[Gorrik]] },
        { id = 2931, name = [[Zaricotl]] },
        { id = 7057, name = [[Digmaster Shovelphlange]] },
    },
    [4] = {
        { id = 7665, name = [[Grol the Destroyer]] },
        { id = 7666, name = [[Archmage Allistarj]] },
        { id = 7667, name = [[Lady Sevine]] },
        { id = 7728, name = [[Kirith the Damned]] },
        { id = 7851, name = [[Nethergarde Elite]] },
        { id = 8296, name = [[Mojo the Twisted]] },
        { id = 8297, name = [[Magronos the Unyielding]] },
        { id = 8298, name = [[Akubar the Seer]] },
        { id = 8299, name = [[Spiteflayer]] },
        { id = 8300, name = [[Ravage]] },
        { id = 8301, name = [[Clack the Reaver]] },
        { id = 8302, name = [[Deatheye]] },
        { id = 8303, name = [[Grunter]] },
        { id = 8304, name = [[Dreadscorn]] },
        { id = 8609, name = [[Alexandra Constantine]] },
        { id = 8716, name = [[Dreadlord]] },
        { id = 8717, name = [[Felguard Elite]] },
        { id = 8718, name = [[Manahound]] },
        { id = 12396, name = [[Doomguard Commander]] },
    },
    [8] = {
        { id = 763, name = [[Lost One Chieftain]] },
        { id = 1106, name = [[Lost One Cook]] },
        { id = 6026, name = [[Breyk]] },
        { id = 12900, name = [[Somnus]] },
        { id = 14445, name = [[Lord Captain Wyrmak]] },
        { id = 14446, name = [[Fingat]] },
        { id = 14447, name = [[Gilmorian]] },
        { id = 14448, name = [[Molt Thorn]] },
    },
    [10] = {
        { id = 503, name = [[Lord Malathrom]] },
        { id = 507, name = [[Fenros]] },
        { id = 521, name = [[Lupos]] },
        { id = 522, name = [[Mor\]] },
        { id = 534, name = [[Nefaru]] },
        { id = 574, name = [[Naraxis]] },
        { id = 771, name = [[Commander Felstrom]] },
        { id = 1200, name = [[Morbent Fel]] },
        { id = 2409, name = [[Felicia Maline]] },
    },
    [11] = {
        { id = 1037, name = [[Dragonmaw Battlemaster]] },
        { id = 1112, name = [[Leech Widow]] },
        { id = 1140, name = [[Razormaw Matriarch]] },
        { id = 1364, name = [[Balgaras the Foul]] },
        { id = 1571, name = [[Shellei Brondir]] },
        { id = 2090, name = [[Ma\]] },
        { id = 2091, name = [[Chieftain Nek\]] },
        { id = 2108, name = [[Garneg Charskull]] },
        { id = 5185, name = [[Hammerhead Shark]] },
        { id = 12899, name = [[Axtroz]] },
        { id = 14424, name = [[Mirelow]] },
        { id = 14425, name = [[Gnawbone]] },
        { id = 14433, name = [[Sludginn]] },
    },
    [12] = {
        { id = 61, name = [[Thuros Lightfingers]] },
        { id = 79, name = [[Narg the Taskmaster]] },
        { id = 99, name = [[Morgaine the Sly]] },
        { id = 100, name = [[Gruff Swiftbite]] },
        { id = 448, name = [[Hogger]] },
        { id = 471, name = [[Mother Fang]] },
        { id = 472, name = [[Fedfennel]] },
        { id = 14390, name = [[Expeditionary Mountaineer]] },
        { id = 14393, name = [[Expeditionary Priest]] },
    },
    [14] = {
        { id = 5808, name = [[Warlord Kolkanis]] },
        { id = 5809, name = [[Watch Commander Zalaphil]] },
        { id = 5822, name = [[Felweaver Scornn]] },
        { id = 5823, name = [[Death Flayer]] },
        { id = 5824, name = [[Captain Flat Tusk]] },
        { id = 5826, name = [[Geolord Mottle]] },
    },
    [15] = {
        { id = 4321, name = [[Baldruc]] },
        { id = 4339, name = [[Brimgore]] },
        { id = 4380, name = [[Darkmist Widow]] },
        { id = 4500, name = [[Overlord Mok\]] },
        { id = 10321, name = [[Emberstrife]] },
        { id = 11899, name = [[Shardi]] },
        { id = 14230, name = [[Burgle Eye]] },
        { id = 14231, name = [[Drogoth the Roamer]] },
        { id = 14234, name = [[Hayoc]] },
        { id = 14236, name = [[Lord Angler]] },
        { id = 14237, name = [[Oozeworm]] },
        { id = 15552, name = [[Doctor Weavil]] },
        { id = 16072, name = [[Tidelord Rrurgaz]] },
    },
    [16] = {
        { id = 6118, name = [[Varo\]] },
        { id = 6134, name = [[Lord Arkkoroc]] },
        { id = 6140, name = [[Hetaera]] },
        { id = 6646, name = [[Monnos the Elder]] },
        { id = 6647, name = [[Magister Hawkhelm]] },
        { id = 6648, name = [[Antilos]] },
        { id = 6649, name = [[Lady Sesspira]] },
        { id = 6650, name = [[General Fangferror]] },
        { id = 6651, name = [[Gatekeeper Rageroar]] },
        { id = 6652, name = [[Master Feardred]] },
        { id = 8610, name = [[Kroum]] },
        { id = 8660, name = [[The Evalcharr]] },
        { id = 8756, name = [[Raytaf]] },
        { id = 8757, name = [[Shahiar]] },
        { id = 8758, name = [[Zaman]] },
        { id = 12125, name = [[Mammoth Shark]] },
        { id = 12577, name = [[Jarrodenus]] },
        { id = 13278, name = [[Duke Hydraxis]] },
        { id = 13322, name = [[Hydraxian Honor Guard]] },
        { id = 13896, name = [[Scalebeard]] },
        { id = 14464, name = [[Avalanchion]] },
    },
    [17] = {
        { id = 3253, name = [[Silithid Harvester]] },
        { id = 3270, name = [[Elder Mystic Razorsnout]] },
        { id = 3295, name = [[Sludge Beast]] },
        { id = 3338, name = [[Sergra Darkthorn]] },
        { id = 3398, name = [[Gesharahan]] },
        { id = 3470, name = [[Rathorian]] },
        { id = 3615, name = [[Devrak]] },
        { id = 3652, name = [[Trigore the Lasher]] },
        { id = 3655, name = [[Mad Magglish]] },
        { id = 3672, name = [[Boahn]] },
        { id = 5797, name = [[Aean Swiftriver]] },
        { id = 5798, name = [[Thora Feathermoon]] },
        { id = 5799, name = [[Hannah Bladeleaf]] },
        { id = 5800, name = [[Marcus Bel]] },
        { id = 5827, name = [[Brontus]] },
        { id = 5828, name = [[Humar the Pridelord]] },
        { id = 5829, name = [[Snort the Heckler]] },
        { id = 5830, name = [[Sister Rathtalon]] },
        { id = 5831, name = [[Swiftmane]] },
        { id = 5832, name = [[Thunderstomp]] },
        { id = 5834, name = [[Azzere the Skyblade]] },
        { id = 5835, name = [[Foreman Grills]] },
        { id = 5836, name = [[Engineer Whirleygig]] },
        { id = 5837, name = [[Stonearm]] },
        { id = 5838, name = [[Brokespear]] },
        { id = 5841, name = [[Rocklance]] },
        { id = 5842, name = [[Takk the Leaper]] },
        { id = 5847, name = [[Heggin Stonewhisker]] },
        { id = 5848, name = [[Malgin Barleybrew]] },
        { id = 5849, name = [[Digger Flameforge]] },
        { id = 5851, name = [[Captain Gerogg Hammertoe]] },
        { id = 5859, name = [[Hagg Taurenbane]] },
        { id = 5863, name = [[Geopriest Gukk\]] },
        { id = 5864, name = [[Swinegart Spearhide]] },
        { id = 5865, name = [[Dishu]] },
        { id = 7233, name = [[Taskmaster Fizzule]] },
        { id = 7288, name = [[Grand Foreman Puzik Gallywix]] },
        { id = 7895, name = [[Ambassador Bloodrage]] },
        { id = 10378, name = [[Omusa Thunderhorn]] },
        { id = 12865, name = [[Ambassador Malcin]] },
        { id = 14717, name = [[Horde Elite]] },
        { id = 14754, name = [[Kelm Hargunth]] },
        { id = 14781, name = [[Captain Shatterskull]] },
        { id = 15804, name = [[Lesser Resonating Crystal]] },
        { id = 15805, name = [[Minor Resonating Crystal]] },
        { id = 16227, name = [[Bragok]] },
    },
    [28] = {
        { id = 1837, name = [[Scarlet Judge]] },
        { id = 1838, name = [[Scarlet Interrogator]] },
        { id = 1839, name = [[Scarlet High Clerist]] },
        { id = 1841, name = [[Scarlet Executioner]] },
        { id = 1842, name = [[Highlord Taelan Fordring]] },
        { id = 1843, name = [[Foreman Jerris]] },
        { id = 1844, name = [[Foreman Marcrid]] },
        { id = 1846, name = [[High Protector Lorik]] },
        { id = 1847, name = [[Foulmane]] },
        { id = 1848, name = [[Lord Maldazzar]] },
        { id = 1850, name = [[Putridius]] },
        { id = 1851, name = [[The Husk]] },
        { id = 1852, name = [[Araj the Summoner]] },
        { id = 1885, name = [[Scarlet Smith]] },
        { id = 11023, name = [[Weldon Barov]] },
        { id = 12425, name = [[Flint Shadowmore]] },
        { id = 12596, name = [[Bibilfaz Featherwhistle]] },
    },
    [33] = {
        { id = 469, name = [[Lieutenant Doren]] },
        { id = 680, name = [[Mosh\]] },
        { id = 723, name = [[Mosh\]] },
        { id = 728, name = [[Bhag\]] },
        { id = 730, name = [[Tethis]] },
        { id = 731, name = [[King Bangalash]] },
        { id = 818, name = [[Mai\]] },
        { id = 875, name = [[Saltscale Tide Lord]] },
        { id = 1060, name = [[Mogh the Undying]] },
        { id = 1387, name = [[Thysta]] },
        { id = 1492, name = [[Gorlash]] },
        { id = 1493, name = [[Mok\]] },
        { id = 1552, name = [[Scale Belly]] },
        { id = 1559, name = [[King Mukla]] },
        { id = 2464, name = [[Commander Aggro\]] },
        { id = 2541, name = [[Lord Sakrasis]] },
        { id = 2635, name = [[Elder Saltwater Crocolisk]] },
        { id = 2858, name = [[Gringer]] },
        { id = 2859, name = [[Gyll]] },
        { id = 11383, name = [[High Priestess Hai\]] },
        { id = 14487, name = [[Gluggle]] },
        { id = 14488, name = [[Roloch]] },
        { id = 14490, name = [[Rippa]] },
        { id = 14491, name = [[Kurmokk]] },
        { id = 14492, name = [[Verifonix]] },
        { id = 14875, name = [[Molthor]] },
        { id = 14876, name = [[Zandalar Headshrinker]] },
        { id = 14902, name = [[Jin\]] },
        { id = 14903, name = [[Al\]] },
        { id = 14904, name = [[Maywiki of Zuldazar]] },
        { id = 14905, name = [[Falthir the Sightless]] },
        { id = 14910, name = [[Exzhal]] },
        { id = 14911, name = [[Zandalar Enforcer]] },
        { id = 14912, name = [[Captured Hakkari Zealot]] },
        { id = 14921, name = [[Rin\]] },
        { id = 15070, name = [[Vinchaxa]] },
        { id = 15076, name = [[Zandalarian Emissary]] },
        { id = 15080, name = [[Servant of the Hand]] },
        { id = 16096, name = [[Steamwheedle Bruiser]] },
    },
    [36] = {
        { id = 2257, name = [[Mug\]] },
        { id = 2258, name = [[Stone Fury]] },
        { id = 2417, name = [[Grel\]] },
        { id = 2420, name = [[Targ]] },
        { id = 2421, name = [[Muckrake]] },
        { id = 2422, name = [[Glommus]] },
        { id = 2447, name = [[Narillasanz]] },
        { id = 2452, name = [[Skhowl]] },
        { id = 2453, name = [[Lo\]] },
        { id = 3984, name = [[Nancy Vishas]] },
        { id = 3985, name = [[Grandpa Vishas]] },
        { id = 13085, name = [[Myrokos Silentform]] },
        { id = 13217, name = [[Thanthaldis Snowgleam]] },
        { id = 13219, name = [[Jekyll Flandring]] },
        { id = 13602, name = [[The Abominable Greench]] },
        { id = 13777, name = [[Sergeant Durgen Stormpike]] },
        { id = 13840, name = [[Warmaster Laggrond]] },
        { id = 13841, name = [[Lieutenant Haggerdin]] },
        { id = 14221, name = [[Gravis Slipknot]] },
        { id = 14222, name = [[Araga]] },
        { id = 14223, name = [[Cranky Benj]] },
        { id = 14281, name = [[Jimmy the Bleeder]] },
        { id = 14284, name = [[Stormpike Battleguard]] },
        { id = 14285, name = [[Frostwolf Battleguard]] },
        { id = 16392, name = [[Captain Armando Ossex]] },
    },
    [38] = {
        { id = 1210, name = [[Chok\]] },
        { id = 1225, name = [[Ol\]] },
        { id = 1398, name = [[Boss Galgosh]] },
        { id = 1399, name = [[Magosh]] },
        { id = 1425, name = [[Grizlak]] },
        { id = 1572, name = [[Thorgrum Borrelson]] },
        { id = 2476, name = [[Large Loch Crocolisk]] },
        { id = 2932, name = [[Magregan Deepshadow]] },
        { id = 4872, name = [[Obsidian Golem]] },
        { id = 14266, name = [[Shanda the Spinner]] },
        { id = 14267, name = [[Emogg the Crusher]] },
        { id = 14268, name = [[Lord Condar]] },
    },
    [40] = {
        { id = 234, name = [[Gryan Stoutmantle]] },
        { id = 462, name = [[Vultros]] },
        { id = 506, name = [[Sergeant Brashclaw]] },
        { id = 519, name = [[Slark]] },
        { id = 520, name = [[Brack]] },
        { id = 523, name = [[Thor]] },
        { id = 572, name = [[Leprithus]] },
        { id = 596, name = [[Brainwashed Noble]] },
        { id = 599, name = [[Marisa du\]] },
        { id = 626, name = [[Foreman Thistlenettle]] },
        { id = 1424, name = [[Master Digger]] },
        { id = 7053, name = [[Klaven Mortwake]] },
    },
    [44] = {
        { id = 334, name = [[Gath\]] },
        { id = 335, name = [[Singe]] },
        { id = 349, name = [[Corporal Keeshan]] },
        { id = 397, name = [[Morganth]] },
        { id = 486, name = [[Tharil\]] },
        { id = 584, name = [[Kazon]] },
        { id = 616, name = [[Chatter]] },
        { id = 931, name = [[Ariena Stormfeather]] },
        { id = 947, name = [[Rohh the Silent]] },
        { id = 7009, name = [[Arantir]] },
        { id = 14269, name = [[Seeker Aqualon]] },
        { id = 14270, name = [[Squiddic]] },
        { id = 14271, name = [[Ribchaser]] },
        { id = 14272, name = [[Snarlflare]] },
        { id = 14273, name = [[Boulderheart]] },
        { id = 14357, name = [[Lake Thresher]] },
    },
    [45] = {
        { id = 2597, name = [[Lord Falconcrest]] },
        { id = 2598, name = [[Darbel Montrose]] },
        { id = 2599, name = [[Otto]] },
        { id = 2600, name = [[Singer]] },
        { id = 2601, name = [[Foulbelly]] },
        { id = 2602, name = [[Ruul Onestone]] },
        { id = 2603, name = [[Kovork]] },
        { id = 2604, name = [[Molok the Crusher]] },
        { id = 2605, name = [[Zalas Witherbark]] },
        { id = 2606, name = [[Nimar the Slayer]] },
        { id = 2607, name = [[Prince Galen Trollbane]] },
        { id = 2609, name = [[Geomancer Flintdagger]] },
        { id = 2611, name = [[Fozruk]] },
        { id = 2612, name = [[Lieutenant Valorcall]] },
        { id = 2773, name = [[Or\]] },
        { id = 2779, name = [[Prince Nazjak]] },
        { id = 2780, name = [[Caretaker Nevlin]] },
        { id = 2781, name = [[Caretaker Weston]] },
        { id = 2782, name = [[Caretaker Alaric]] },
        { id = 2783, name = [[Marez Cowl]] },
        { id = 2835, name = [[Cedrik Prose]] },
        { id = 2851, name = [[Urda]] },
        { id = 15126, name = [[Rutherford Twing]] },
        { id = 15127, name = [[Samuel Hawke]] },
        { id = 15128, name = [[Defiler Elite]] },
        { id = 15130, name = [[League of Arathor Elite]] },
    },
    [46] = {
        { id = 2299, name = [[Borgus Stoutarm]] },
        { id = 8976, name = [[Hematos]] },
        { id = 8978, name = [[Thauris Balgarr]] },
        { id = 8979, name = [[Gruklash]] },
        { id = 8981, name = [[Malfunctioning Reaver]] },
        { id = 9459, name = [[Cyrus Therepentous]] },
        { id = 9520, name = [[Grark Lorkrub]] },
        { id = 9602, name = [[Hahk\]] },
        { id = 9604, name = [[Gorgon\]] },
        { id = 10077, name = [[Deathmaw]] },
        { id = 10078, name = [[Terrorspark]] },
        { id = 10119, name = [[Volchan]] },
        { id = 13177, name = [[Vahgruk]] },
        { id = 14529, name = [[Franklin the Friendly]] },
    },
    [47] = {
        { id = 4314, name = [[Gorkas]] },
        { id = 5718, name = [[Rothos]] },
        { id = 7977, name = [[Gammerita]] },
        { id = 7995, name = [[Vile Priestess Hexx]] },
        { id = 7996, name = [[Qiaga the Keeper]] },
        { id = 8018, name = [[Guthrum Thunderfist]] },
        { id = 8210, name = [[Razortalon]] },
        { id = 8211, name = [[Old Cliff Jumper]] },
        { id = 8212, name = [[The Reak]] },
        { id = 8213, name = [[Ironback]] },
        { id = 8214, name = [[Jalinde Summerdrake]] },
        { id = 8215, name = [[Grimungous]] },
        { id = 8216, name = [[Retherokk the Berserker]] },
        { id = 8217, name = [[Mith\]] },
        { id = 8218, name = [[Witherheart the Stalker]] },
        { id = 8219, name = [[Zul\]] },
        { id = 8636, name = [[Morta\]] },
        { id = 10802, name = [[Hitah\]] },
        { id = 12477, name = [[Verdantine Boughguard]] },
        { id = 12478, name = [[Verdantine Oracle]] },
        { id = 12479, name = [[Verdantine Tree Warder]] },
        { id = 12496, name = [[Dreamtracker]] },
    },
    [51] = {
        { id = 2941, name = [[Lanie Reed]] },
        { id = 3305, name = [[Grisha]] },
        { id = 5833, name = [[Margol the Rager]] },
        { id = 8277, name = [[Rekk\]] },
        { id = 8278, name = [[Smoldar]] },
        { id = 8279, name = [[Faulty War Golem]] },
        { id = 8280, name = [[Shleipnarr]] },
        { id = 8281, name = [[Scald]] },
        { id = 8282, name = [[Highlord Mastrogonde]] },
        { id = 8283, name = [[Slave Master Blackheart]] },
        { id = 8400, name = [[Obsidion]] },
        { id = 8447, name = [[Clunk]] },
        { id = 8479, name = [[Kalaran Windblade]] },
        { id = 8504, name = [[Dark Iron Sentry]] },
        { id = 14621, name = [[Overseer Maltorius]] },
    },
    [85] = {
        { id = 1531, name = [[Lost Soul]] },
        { id = 1533, name = [[Tormented Spirit]] },
        { id = 1910, name = [[Muad]] },
        { id = 1911, name = [[Deeb]] },
        { id = 1936, name = [[Farmer Solliden]] },
        { id = 5435, name = [[Sand Shark]] },
        { id = 10356, name = [[Bayne]] },
        { id = 10357, name = [[Ressan the Needler]] },
        { id = 10358, name = [[Fellicent\]] },
        { id = 10359, name = [[Sri\]] },
        { id = 11022, name = [[Alexi Barov]] },
        { id = 15195, name = [[Wickerman Guardian]] },
        { id = 15197, name = [[Darkcaller Yanka]] },
    },
    [130] = {
        { id = 1920, name = [[Dalaran Spellscribe]] },
        { id = 1944, name = [[Rot Hide Bruiser]] },
        { id = 1947, name = [[Thule Ravenclaw]] },
        { id = 1948, name = [[Snarlmane]] },
        { id = 2106, name = [[Apothecary Berard]] },
        { id = 2226, name = [[Karos Razok]] },
        { id = 2283, name = [[Ravenclaw Regent]] },
        { id = 12431, name = [[Gorefang]] },
        { id = 12432, name = [[Old Vicejaw]] },
        { id = 12433, name = [[Krethis Shadowspinner]] },
    },
    [139] = {
        { id = 1855, name = [[Tirion Fordring]] },
        { id = 10817, name = [[Duggan Wildhammer]] },
        { id = 10821, name = [[Hed\]] },
        { id = 10822, name = [[Warlord Thresh\]] },
        { id = 10823, name = [[Zul\]] },
        { id = 10824, name = [[Ranger Lord Hawkspear]] },
        { id = 10825, name = [[Gish the Unmoving]] },
        { id = 10826, name = [[Lord Darkscythe]] },
        { id = 10827, name = [[Deathspeaker Selendre]] },
        { id = 10828, name = [[High General Abbendis]] },
        { id = 11102, name = [[Argent Rider]] },
        { id = 11878, name = [[Nathanos Blightcaller]] },
        { id = 11896, name = [[Borelgore]] },
        { id = 11897, name = [[Duskwing]] },
        { id = 11898, name = [[Crusader Lord Valdelmar]] },
        { id = 12262, name = [[Ziggurat Protector]] },
        { id = 12263, name = [[Slaughterhouse Protector]] },
        { id = 12337, name = [[Crimson Courier]] },
        { id = 12617, name = [[Khaelyn Steelwing]] },
        { id = 12636, name = [[Georgia]] },
        { id = 14494, name = [[Eris Havenfire]] },
        { id = 15162, name = [[Scarlet Inquisitor]] },
        { id = 16112, name = [[Korfax, Champion of the Light]] },
        { id = 16113, name = [[Father Inigo Montoy]] },
        { id = 16114, name = [[Scarlet Commander Marjhan]] },
        { id = 16115, name = [[Commander Eligor Dawnbringer]] },
        { id = 16116, name = [[Archmage Angela Dosantos]] },
        { id = 16131, name = [[Rohan the Assassin]] },
        { id = 16132, name = [[Huntsman Leopold]] },
        { id = 16133, name = [[Mataus the Wrathcaster]] },
        { id = 16134, name = [[Rimblat Earthshatter]] },
        { id = 16135, name = [[Rayne]] },
        { id = 16184, name = [[Nerubian Overseer]] },
        { id = 16378, name = [[Argent Sentry]] },
    },
    [141] = {
        { id = 2166, name = [[Oakenscowl]] },
        { id = 3535, name = [[Blackmoss the Fetid]] },
        { id = 3838, name = [[Vesprystus]] },
        { id = 14428, name = [[Uruson]] },
        { id = 14429, name = [[Grimmaw]] },
        { id = 14430, name = [[Duskstalker]] },
        { id = 14431, name = [[Fury Shelda]] },
        { id = 14432, name = [[Threggil]] },
        { id = 16817, name = [[Festival Loremaster]] },
    },
    [148] = {
        { id = 2172, name = [[Strider Clutchmother]] },
        { id = 2175, name = [[Shadowclaw]] },
        { id = 2184, name = [[Lady Moongazer]] },
        { id = 2186, name = [[Carnivous the Breaker]] },
        { id = 2191, name = [[Licillin]] },
        { id = 2192, name = [[Firecaller Radison]] },
        { id = 3841, name = [[Caylais Moonfeather]] },
        { id = 7015, name = [[Flagglemurk the Cruel]] },
        { id = 7016, name = [[Lady Vespira]] },
        { id = 7017, name = [[Lord Sinslayer]] },
    },
    [209] = {
        { id = 3849, name = [[Deathstalker Adamant]] },
        { id = 3850, name = [[Sorcerer Ashcrombe]] },
        { id = 3853, name = [[Shadowfang Moonwalker]] },
        { id = 3854, name = [[Shadowfang Wolfguard]] },
        { id = 3855, name = [[Shadowfang Darksoul]] },
        { id = 3857, name = [[Shadowfang Glutton]] },
        { id = 3859, name = [[Shadowfang Ragetooth]] },
        { id = 3862, name = [[Slavering Worg]] },
        { id = 3863, name = [[Lupine Horror]] },
        { id = 3872, name = [[Deathsworn Captain]] },
        { id = 3886, name = [[Razorclaw the Butcher]] },
        { id = 3887, name = [[Baron Silverlaine]] },
        { id = 3914, name = [[Rethilgore]] },
        { id = 3927, name = [[Wolf Master Nandos]] },
        { id = 4274, name = [[Fenrus the Devourer]] },
        { id = 4275, name = [[Archmage Arugal]] },
        { id = 4278, name = [[Commander Springvale]] },
        { id = 4279, name = [[Odo the Blindwatcher]] },
        { id = 10000, name = [[Arugal]] },
        { id = 14682, name = [[Sever]] },
    },
    [215] = {
        { id = 3056, name = [[Ghost Howl]] },
        { id = 3068, name = [[Mazzranache]] },
        { id = 5785, name = [[Sister Hatelash]] },
        { id = 5786, name = [[Snagglespear]] },
        { id = 5787, name = [[Enforcer Emilgund]] },
        { id = 5807, name = [[The Rake]] },
        { id = 14823, name = [[Silas Darkmoon]] },
        { id = 14865, name = [[Felinni]] },
    },
    [267] = {
        { id = 2215, name = [[High Executor Darthalia]] },
        { id = 2276, name = [[Magistrate Henry Maleb]] },
        { id = 2304, name = [[Captain Ironhill]] },
        { id = 2389, name = [[Zarise]] },
        { id = 2432, name = [[Darla Harris]] },
        { id = 14275, name = [[Tamra Stormpike]] },
        { id = 14276, name = [[Scargil]] },
        { id = 14277, name = [[Lady Zephris]] },
        { id = 14278, name = [[Ro\]] },
        { id = 14279, name = [[Creepthess]] },
        { id = 14280, name = [[Big Samras]] },
        { id = 15199, name = [[Sergeant Hartman]] },
    },
    [331] = {
        { id = 3691, name = [[Raene Wolfrunner]] },
        { id = 3735, name = [[Apothecary Falthis]] },
        { id = 3773, name = [[Akkrilus]] },
        { id = 3792, name = [[Terrowulf Packlord]] },
        { id = 4267, name = [[Daelyshia]] },
        { id = 5314, name = [[Phantim]] },
        { id = 10559, name = [[Lady Vespia]] },
        { id = 10639, name = [[Rorgish Jowl]] },
        { id = 10640, name = [[Oakpaw]] },
        { id = 10641, name = [[Branch Snapper]] },
        { id = 10642, name = [[Eck\]] },
        { id = 10643, name = [[Mugglefin]] },
        { id = 10644, name = [[Mist Howler]] },
        { id = 10647, name = [[Prince Raze]] },
        { id = 11901, name = [[Andruk]] },
        { id = 12037, name = [[Ursol\]] },
        { id = 12474, name = [[Emeraldon Boughguard]] },
        { id = 12475, name = [[Emeraldon Tree Warder]] },
        { id = 12476, name = [[Emeraldon Oracle]] },
        { id = 12498, name = [[Dreamstalker]] },
        { id = 12616, name = [[Vhulgra]] },
        { id = 12737, name = [[Mastok Wrilehiss]] },
        { id = 12836, name = [[Wandering Protector]] },
        { id = 14715, name = [[Silverwing Elite]] },
        { id = 14733, name = [[Sentinel Farsong]] },
        { id = 14753, name = [[Illiyana Moonblaze]] },
    },
    [357] = {
        { id = 4319, name = [[Thyssiana]] },
        { id = 5312, name = [[Lethlas]] },
        { id = 5317, name = [[Jademir Oracle]] },
        { id = 5319, name = [[Jademir Tree Warder]] },
        { id = 5320, name = [[Jademir Boughguard]] },
        { id = 5343, name = [[Lady Szallah]] },
        { id = 5345, name = [[Diamond Head]] },
        { id = 5346, name = [[Bloodroar the Stalker]] },
        { id = 5347, name = [[Antilus the Soarer]] },
        { id = 5349, name = [[Arash-ethis]] },
        { id = 5350, name = [[Qirot]] },
        { id = 5352, name = [[Old Grizzlegut]] },
        { id = 5354, name = [[Gnarl Leafbrother]] },
        { id = 5356, name = [[Snarler]] },
        { id = 7875, name = [[Hadoken Swiftstrider]] },
        { id = 8019, name = [[Fyldren Moonfeather]] },
        { id = 8020, name = [[Shyn]] },
        { id = 10182, name = [[Rexxar]] },
        { id = 10204, name = [[Misha]] },
        { id = 12497, name = [[Dreamroarer]] },
        { id = 12803, name = [[Lord Lakmaeran]] },
        { id = 15771, name = [[Major Resonating Crystal]] },
    },
    [361] = {
        { id = 7104, name = [[Dessecus]] },
        { id = 7137, name = [[Immolatus]] },
        { id = 9516, name = [[Lord Banehollow]] },
        { id = 11900, name = [[Brakkar]] },
        { id = 12578, name = [[Mishellena]] },
        { id = 14339, name = [[Death Howl]] },
        { id = 14340, name = [[Alshirr Banebreath]] },
        { id = 14342, name = [[Ragepaw]] },
        { id = 14343, name = [[Olm the Wise]] },
        { id = 14344, name = [[Mongress]] },
        { id = 14345, name = [[The Ongar]] },
        { id = 14467, name = [[Kroshius]] },
    },
    [400] = {
        { id = 4132, name = [[Silithid Ravager]] },
        { id = 4317, name = [[Nyse]] },
        { id = 4499, name = [[Rok\]] },
        { id = 5933, name = [[Achellios the Banished]] },
        { id = 5934, name = [[Heartrazor]] },
        { id = 5935, name = [[Ironeye the Invincible]] },
        { id = 5937, name = [[Vile Sting]] },
        { id = 10992, name = [[Enraged Panther]] },
        { id = 14426, name = [[Harb Foulmountain]] },
        { id = 14427, name = [[Gibblesnik]] },
        { id = 15769, name = [[Resonating Crystal]] },
        { id = 15770, name = [[Greater Resonating Crystal]] },
    },
    [405] = {
        { id = 5760, name = [[Lord Azrethoc]] },
        { id = 6706, name = [[Baritanas Skyriver]] },
        { id = 6726, name = [[Thalon]] },
        { id = 11688, name = [[Cursed Centaur]] },
        { id = 12239, name = [[Spirit of Gelk]] },
        { id = 12240, name = [[Spirit of Kolk]] },
        { id = 12241, name = [[Spirit of Magra]] },
        { id = 13697, name = [[Cavindra]] },
        { id = 13718, name = [[The Nameless Prophet]] },
        { id = 14225, name = [[Prince Kellen]] },
        { id = 14226, name = [[Kaskk]] },
        { id = 14227, name = [[Hissperak]] },
        { id = 14228, name = [[Giggler]] },
        { id = 14229, name = [[Accursed Slitherblade]] },
    },
    [406] = {
        { id = 4015, name = [[Pridewing Patriarch]] },
        { id = 4030, name = [[Vengeful Ancient]] },
        { id = 4066, name = [[Nal\]] },
        { id = 4312, name = [[Tharm]] },
        { id = 4407, name = [[Teloren]] },
        { id = 4409, name = [[Gatekeeper Kordurus]] },
        { id = 5915, name = [[Brother Ravenoak]] },
        { id = 5916, name = [[Sentinel Amarassan]] },
        { id = 5928, name = [[Sorrow Wing]] },
        { id = 5930, name = [[Sister Riven]] },
        { id = 5931, name = [[Foreman Rigger]] },
        { id = 5932, name = [[Taskmaster Whipfang]] },
        { id = 8518, name = [[Rynthariel the Keymaster]] },
        { id = 11921, name = [[Besseleth]] },
        { id = 12579, name = [[Bloodfury Ripper]] },
    },
    [440] = {
        { id = 5467, name = [[Deep Dweller]] },
        { id = 7823, name = [[Bera Stonehammer]] },
        { id = 7824, name = [[Bulkrek Ragefist]] },
        { id = 8196, name = [[Occulus]] },
        { id = 8197, name = [[Chronalis]] },
        { id = 8198, name = [[Tick]] },
        { id = 8199, name = [[Warleader Krazzilak]] },
        { id = 8200, name = [[Jin\]] },
        { id = 8201, name = [[Omgorn the Lost]] },
        { id = 8202, name = [[Cyclok the Mad]] },
        { id = 8203, name = [[Kregg Keelhaul]] },
        { id = 8204, name = [[Soriid the Devourer]] },
        { id = 8205, name = [[Haarka the Ravenous]] },
        { id = 8207, name = [[Greater Firebird]] },
        { id = 8208, name = [[Murderous Blisterpaw]] },
        { id = 12124, name = [[Great Shark]] },
    },
    [490] = {
        { id = 6581, name = [[Ravasaur Matriarch]] },
        { id = 6582, name = [[Clutchmother Zavas]] },
        { id = 6583, name = [[Gruff]] },
        { id = 6584, name = [[King Mosh]] },
        { id = 6585, name = [[Uhk\]] },
        { id = 9376, name = [[Blazerunner]] },
        { id = 10583, name = [[Gryfe]] },
        { id = 14461, name = [[Baron Charr]] },
        { id = 14527, name = [[Simone the Inconspicuous]] },
    },
    [491] = {
        { id = 4420, name = [[Overlord Ramtusk]] },
        { id = 4421, name = [[Charlga Razorflank]] },
        { id = 4422, name = [[Agathelos the Raging]] },
        { id = 4424, name = [[Aggem Thorncurse]] },
        { id = 4425, name = [[Blind Hunter]] },
        { id = 4427, name = [[Ward Guardian]] },
        { id = 4428, name = [[Death Speaker Jargba]] },
        { id = 4438, name = [[Razorfen Spearhide]] },
        { id = 4440, name = [[Razorfen Totemic]] },
        { id = 4508, name = [[Willix the Importer]] },
        { id = 4512, name = [[Rotting Agam\]] },
        { id = 4520, name = [[Razorfen Geomancer]] },
        { id = 4539, name = [[Greater Kraul Bat]] },
        { id = 4541, name = [[Blood of Agamaggan]] },
        { id = 4842, name = [[Earthcaller Halmgar]] },
        { id = 6168, name = [[Roogug]] },
    },
    [493] = {
        { id = 10897, name = [[Sindrayl]] },
        { id = 11832, name = [[Keeper Remulos]] },
        { id = 12740, name = [[Faustron]] },
        { id = 15961, name = [[Lunar Festival Sentinel]] },
    },
    [618] = {
        { id = 10196, name = [[General Colbatann]] },
        { id = 10197, name = [[Mezzir the Howler]] },
        { id = 10198, name = [[Kashoch the Reaver]] },
        { id = 10199, name = [[Grizzle Snowpaw]] },
        { id = 10200, name = [[Rak\]] },
        { id = 10201, name = [[Lady Hederine]] },
        { id = 10202, name = [[Azurous]] },
        { id = 10662, name = [[Spellmaw]] },
        { id = 10663, name = [[Manaclaw]] },
        { id = 10664, name = [[Scryer]] },
        { id = 10738, name = [[High Chief Winterfall]] },
        { id = 10806, name = [[Ursius]] },
        { id = 10807, name = [[Brumeran]] },
        { id = 10929, name = [[Haleh]] },
        { id = 11138, name = [[Maethrya]] },
        { id = 11139, name = [[Yugrek]] },
        { id = 14348, name = [[Earthcaller Franzahl]] },
        { id = 14457, name = [[Princess Tempestria]] },
        { id = 14531, name = [[Artorius the Amiable]] },
    },
    [717] = {
        { id = 1663, name = [[Dextren Ward]] },
        { id = 1666, name = [[Kam Deepfury]] },
        { id = 1696, name = [[Targorr the Dread]] },
        { id = 1716, name = [[Bazil Thredd]] },
        { id = 1717, name = [[Hamhock]] },
        { id = 1720, name = [[Bruegal Ironknuckle]] },
    },
    [718] = {
        { id = 3653, name = [[Kresh]] },
        { id = 3669, name = [[Lord Cobrahn]] },
        { id = 3670, name = [[Lord Pythas]] },
        { id = 3673, name = [[Lord Serpentis]] },
        { id = 3674, name = [[Skum]] },
        { id = 3678, name = [[Disciple of Naralex]] },
        { id = 5755, name = [[Deviate Viper]] },
        { id = 5775, name = [[Verdan the Everliving]] },
        { id = 5912, name = [[Deviate Faerie Dragon]] },
    },
    [719] = {
        { id = 4819, name = [[Blindlight Muckdweller]] },
        { id = 4820, name = [[Blindlight Oracle]] },
        { id = 4829, name = [[Aku\]] },
        { id = 4830, name = [[Old Serra\]] },
        { id = 4831, name = [[Lady Sarevess]] },
        { id = 4832, name = [[Twilight Lord Kelris]] },
        { id = 4887, name = [[Ghamoo-ra]] },
        { id = 6243, name = [[Gelihast]] },
        { id = 12902, name = [[Lorgus Jett]] },
    },
    [721] = {
        { id = 6228, name = [[Dark Iron Ambassador]] },
        { id = 6230, name = [[Peacekeeper Security Suit]] },
        { id = 7079, name = [[Viscous Fallout]] },
        { id = 7800, name = [[Mekgineer Thermaplugg]] },
        { id = 7998, name = [[Blastmaster Emi Shortfuse]] },
    },
    [722] = {
        { id = 7354, name = [[Ragglesnout]] },
        { id = 7357, name = [[Mordresh Fire Eye]] },
        { id = 7358, name = [[Amnennar the Coldbringer]] },
        { id = 8567, name = [[Glutton]] },
        { id = 14686, name = [[Lady Falther\]] },
    },
    [796] = {
        { id = 3974, name = [[Houndmaster Loksey]] },
        { id = 3975, name = [[Herod]] },
        { id = 3976, name = [[Scarlet Commander Mograine]] },
        { id = 3977, name = [[High Inquisitor Whitemane]] },
        { id = 3983, name = [[Interrogator Vishas]] },
        { id = 4304, name = [[Scarlet Tracking Hound]] },
        { id = 4542, name = [[High Inquisitor Fairbanks]] },
        { id = 4543, name = [[Bloodmage Thalnos]] },
        { id = 6487, name = [[Arcanist Doan]] },
        { id = 6488, name = [[Fallen Champion]] },
        { id = 6489, name = [[Ironspine]] },
        { id = 6490, name = [[Azshir the Sleepless]] },
    },
    [1176] = {
        { id = 7267, name = [[Chief Ukorz Sandscalp]] },
        { id = 7271, name = [[Witch Doctor Zum\]] },
        { id = 7272, name = [[Theka the Martyr]] },
        { id = 7274, name = [[Sandfury Executioner]] },
        { id = 7604, name = [[Sergeant Bly]] },
        { id = 7605, name = [[Raven]] },
        { id = 7606, name = [[Oro Eyegouge]] },
        { id = 7607, name = [[Weegli Blastfuse]] },
        { id = 7608, name = [[Murta Grimgut]] },
        { id = 7795, name = [[Hydromancer Velratha]] },
        { id = 7797, name = [[Ruuzlu]] },
        { id = 8120, name = [[Sul\]] },
        { id = 8127, name = [[Antu\]] },
        { id = 10080, name = [[Sandarr Dunereaver]] },
        { id = 10081, name = [[Dustwraith]] },
        { id = 10082, name = [[Zerillis]] },
    },
    [1337] = {
        { id = 2748, name = [[Archaedas]] },
        { id = 4854, name = [[Grimlok]] },
        { id = 4857, name = [[Stone Keeper]] },
        { id = 6906, name = [[Baelog]] },
        { id = 6907, name = [[Eric "The Swift"]] },
        { id = 6908, name = [[Olaf]] },
        { id = 6910, name = [[Revelosh]] },
        { id = 7023, name = [[Obsidian Sentinel]] },
        { id = 7206, name = [[Ancient Stone Keeper]] },
        { id = 7291, name = [[Galgann Firehammer]] },
        { id = 10120, name = [[Vault Warder]] },
    },
    [1377] = {
        { id = 14347, name = [[Highlord Demitrian]] },
        { id = 14454, name = [[The Windreaver]] },
        { id = 14471, name = [[Setis]] },
        { id = 14472, name = [[Gretheer]] },
        { id = 14473, name = [[Lapress]] },
        { id = 14474, name = [[Zora]] },
        { id = 14475, name = [[Rex Ashil]] },
        { id = 14476, name = [[Krellack]] },
        { id = 14477, name = [[Grubthor]] },
        { id = 14478, name = [[Huricanian]] },
        { id = 14479, name = [[Twilight Lord Everun]] },
        { id = 14536, name = [[Nelson the Nice]] },
        { id = 15177, name = [[Cloud Skydancer]] },
        { id = 15178, name = [[Runk Windtamer]] },
        { id = 15181, name = [[Commander Mar\]] },
        { id = 15182, name = [[Vish Kozus]] },
        { id = 15184, name = [[Cenarion Hold Infantry]] },
        { id = 15185, name = [[Brood of Nozdormu]] },
        { id = 15196, name = [[Deathclasp]] },
        { id = 15308, name = [[Twilight Prophet]] },
        { id = 15442, name = [[Ironforge Brigade Footman]] },
        { id = 15443, name = [[Janela Stouthammer]] },
        { id = 15444, name = [[Arcanist Nozzlespring]] },
        { id = 15500, name = [[Keyl Swiftclaw]] },
        { id = 15540, name = [[Windcaller Kaldon]] },
        { id = 15541, name = [[Twilight Marauder Morna]] },
        { id = 15609, name = [[Cenarion Scout Landion]] },
        { id = 15610, name = [[Cenarion Scout Azenel]] },
        { id = 15611, name = [[Cenarion Scout Jalia]] },
        { id = 15612, name = [[Krug Skullsplit]] },
        { id = 15613, name = [[Merok Longstride]] },
        { id = 15614, name = [[J.D. Shadesong]] },
        { id = 15615, name = [[Shadow Priestess Shai]] },
        { id = 15616, name = [[Orgrimmar Legion Grunt]] },
        { id = 15617, name = [[Orgrimmar Legion Axe Thrower]] },
        { id = 15693, name = [[Jonathan the Revelator]] },
        { id = 16091, name = [[Dirk Thunderwood]] },
        { id = 17765, name = [[Alliance Silithyst Sentinel]] },
        { id = 17766, name = [[Horde Silithyst Sentinel]] },
    },
    [1477] = {
        { id = 5708, name = [[Spawn of Hakkar]] },
        { id = 5709, name = [[Shade of Eranikus]] },
        { id = 5710, name = [[Jammal\]] },
        { id = 5711, name = [[Ogom the Wretched]] },
        { id = 5712, name = [[Zolo]] },
        { id = 5713, name = [[Gasher]] },
        { id = 5714, name = [[Loro]] },
        { id = 5715, name = [[Hukku]] },
        { id = 5716, name = [[Zul\]] },
        { id = 5717, name = [[Mijan]] },
        { id = 5719, name = [[Morphaz]] },
        { id = 5722, name = [[Hazzas]] },
    },
    [1497] = {
        { id = 347, name = [[Grizzle Halfmane]] },
        { id = 2804, name = [[Kurden Bloodclaw]] },
        { id = 4551, name = [[Michael Garrett]] },
        { id = 11870, name = [[Archibald]] },
        { id = 13839, name = [[Royal Dreadguard]] },
        { id = 14402, name = [[Seeker Cromwell]] },
        { id = 14403, name = [[Seeker Nahr]] },
        { id = 14404, name = [[Seeker Thompson]] },
        { id = 15007, name = [[Sir Malory Wheeler]] },
        { id = 15703, name = [[Senior Sergeant Grimsford]] },
    },
    [1519] = {
        { id = 352, name = [[Dungar Longdrink]] },
        { id = 466, name = [[General Marcus Jonathan]] },
        { id = 3581, name = [[Sewer Beast]] },
        { id = 7410, name = [[Thelman Slatefist]] },
        { id = 8383, name = [[Master Wood]] },
        { id = 11867, name = [[Woo Ping]] },
        { id = 14394, name = [[Major Mattingly]] },
        { id = 14423, name = [[Officer Jaxon]] },
        { id = 14438, name = [[Officer Pomeroy]] },
        { id = 14439, name = [[Officer Brady]] },
        { id = 14721, name = [[Field Marshal Afrasiabi]] },
        { id = 14981, name = [[Elfarran]] },
        { id = 15008, name = [[Lady Hoteshem]] },
        { id = 15708, name = [[Master Sergeant Maclure]] },
    },
    [1537] = {
        { id = 857, name = [[Donal Osgood]] },
        { id = 1573, name = [[Gryth Thurden]] },
        { id = 11865, name = [[Buliwyf Stonehand]] },
        { id = 12197, name = [[Glordrum Steelbeard]] },
        { id = 13084, name = [[Bixi Wobblebonk]] },
        { id = 14363, name = [[Thief Catcher Shadowdelve]] },
        { id = 14365, name = [[Thief Catcher Farmountain]] },
        { id = 14367, name = [[Thief Catcher Thunderbrew]] },
        { id = 14982, name = [[Lylandris]] },
        { id = 15383, name = [[Sergeant Stonebrow]] },
        { id = 15431, name = [[Corporal Carnes]] },
        { id = 15432, name = [[Dame Twinbraid]] },
        { id = 15434, name = [[Private Draxlegauge]] },
        { id = 15437, name = [[Master Nightsong]] },
        { id = 15445, name = [[Sergeant Major Germaine]] },
        { id = 15446, name = [[Bonnie Stoneflayer]] },
        { id = 15448, name = [[Private Porter]] },
        { id = 15450, name = [[Marta Finespindle]] },
        { id = 15451, name = [[Sentinel Silversky]] },
        { id = 15452, name = [[Nurse Stonefield]] },
        { id = 15453, name = [[Keeper Moonshade]] },
        { id = 15455, name = [[Slicky Gastronome]] },
        { id = 15456, name = [[Sarah Sadwhistle]] },
        { id = 15457, name = [[Huntress Swiftriver]] },
        { id = 15539, name = [[General Zog]] },
        { id = 15701, name = [[Field Marshal Snowfall]] },
        { id = 15707, name = [[Master Sergeant Fizzlebolt]] },
    },
    [1581] = {
        { id = 639, name = [[Edwin VanCleef]] },
        { id = 642, name = [[Sneed\]] },
        { id = 644, name = [[Rhahk\]] },
        { id = 645, name = [[Cookie]] },
        { id = 646, name = [[Mr. Smite]] },
        { id = 647, name = [[Captain Greenskin]] },
        { id = 1763, name = [[Gilnid]] },
        { id = 3586, name = [[Miner Johnson]] },
    },
    [1583] = {
        { id = 9196, name = [[Highlord Omokk]] },
        { id = 9217, name = [[Spirestone Lord Magus]] },
        { id = 9218, name = [[Spirestone Battle Lord]] },
        { id = 9219, name = [[Spirestone Butcher]] },
        { id = 9236, name = [[Shadow Hunter Vosh\]] },
        { id = 9237, name = [[War Master Voone]] },
        { id = 9568, name = [[Overlord Wyrmthalak]] },
        { id = 9596, name = [[Bannok Grimaxe]] },
        { id = 9718, name = [[Ghok Bashguud]] },
        { id = 9736, name = [[Quartermaster Zigris]] },
        { id = 10220, name = [[Halycon]] },
        { id = 10257, name = [[Bijou]] },
        { id = 10299, name = [[Scarshield Infiltrator]] },
        { id = 10371, name = [[Rage Talon Captain]] },
        { id = 10376, name = [[Crystal Fang]] },
        { id = 10509, name = [[Jed Runewatcher]] },
        { id = 10596, name = [[Mother Smolderweb]] },
        { id = 10740, name = [[Awbee]] },
        { id = 10762, name = [[Blackhand Thug]] },
        { id = 10899, name = [[Goraluk Anvilcrack]] },
    },
    [1585] = {
        { id = 8923, name = [[Panzor the Invincible]] },
        { id = 8929, name = [[Princess Moira Bronzebeard]] },
        { id = 8982, name = [[Ironhand Guardian]] },
        { id = 8983, name = [[Golem Lord Argelmach]] },
        { id = 9016, name = [[Bael\]] },
        { id = 9017, name = [[Lord Incendius]] },
        { id = 9018, name = [[High Interrogator Gerstahn]] },
        { id = 9019, name = [[Emperor Dagran Thaurissan]] },
        { id = 9020, name = [[Commander Gor\]] },
        { id = 9021, name = [[Kharan Mighthammer]] },
        { id = 9022, name = [[Dughal Stormwing]] },
        { id = 9023, name = [[Marshal Windsor]] },
        { id = 9024, name = [[Pyromancer Loregrain]] },
        { id = 9025, name = [[Lord Roccor]] },
        { id = 9033, name = [[General Angerforge]] },
        { id = 9034, name = [[Hate\]] },
        { id = 9035, name = [[Anger\]] },
        { id = 9036, name = [[Vile\]] },
        { id = 9037, name = [[Gloom\]] },
        { id = 9038, name = [[Seeth\]] },
        { id = 9039, name = [[Doom\]] },
        { id = 9040, name = [[Dope\]] },
        { id = 9041, name = [[Warder Stilgiss]] },
        { id = 9042, name = [[Verek]] },
        { id = 9056, name = [[Fineous Darkvire]] },
        { id = 9156, name = [[Ambassador Flamelash]] },
        { id = 9319, name = [[Houndmaster Grebmar]] },
        { id = 9499, name = [[Plugger Spazzring]] },
        { id = 9500, name = [[Mistress Nagmara]] },
        { id = 9502, name = [[Phalanx]] },
        { id = 9543, name = [[Ribbly Screwspigot]] },
        { id = 9677, name = [[Ograbisi]] },
        { id = 9678, name = [[Shill Dinger]] },
        { id = 9679, name = [[Tobias Seecher]] },
        { id = 9680, name = [[Crest Killer]] },
        { id = 9681, name = [[Jaz]] },
        { id = 9938, name = [[Magmus]] },
    },
    [1637] = {
        { id = 3310, name = [[Doras]] },
        { id = 3890, name = [[Brakgul Deathbringer]] },
        { id = 11868, name = [[Sayoc]] },
        { id = 11871, name = [[Grinning Dog]] },
        { id = 14375, name = [[Scout Stronghand]] },
        { id = 14376, name = [[Scout Manslayer]] },
        { id = 14377, name = [[Scout Tharr]] },
        { id = 14392, name = [[Overlord Runthak]] },
        { id = 14720, name = [[High Overlord Saurfang]] },
        { id = 14942, name = [[Kartra Bloodsnarl]] },
        { id = 15006, name = [[Deze Snowbane]] },
        { id = 15458, name = [[Commander Stronghammer]] },
        { id = 15459, name = [[Miner Cromwell]] },
        { id = 15460, name = [[Grunt Maug]] },
        { id = 15469, name = [[Senior Sergeant T\]] },
        { id = 15477, name = [[Herbalist Proudfeather]] },
        { id = 15508, name = [[Batrider Pele\]] },
        { id = 15512, name = [[Apothecary Jezel]] },
        { id = 15515, name = [[Skinner Jamani]] },
        { id = 15522, name = [[Sergeant Umala]] },
        { id = 15525, name = [[Doctor Serratus]] },
        { id = 15528, name = [[Healer Longrunner]] },
        { id = 15529, name = [[Lady Callow]] },
        { id = 15532, name = [[Stoneguard Clayhoof]] },
        { id = 15533, name = [[Bloodguard Rawtar]] },
        { id = 15534, name = [[Fisherman Lin\]] },
        { id = 15535, name = [[Chief Sharpclaw]] },
        { id = 15700, name = [[Warlord Gorchuk]] },
        { id = 15704, name = [[Senior Sergeant Kai\]] },
        { id = 16788, name = [[Festival Flamekeeper]] },
    },
    [1638] = {
        { id = 2995, name = [[Tal]] },
        { id = 7427, name = [[Taim Ragetotem]] },
        { id = 10360, name = [[Kergul Bloodaxe]] },
        { id = 11869, name = [[Ansekhwa]] },
        { id = 12198, name = [[Martin Lindsey]] },
        { id = 14440, name = [[Hunter Sagewind]] },
        { id = 14441, name = [[Hunter Ragetotem]] },
        { id = 14442, name = [[Hunter Thunderhorn]] },
        { id = 15702, name = [[Senior Sergeant Taiga]] },
        { id = 16818, name = [[Festival Talespinner]] },
    },
    [1657] = {
        { id = 907, name = [[Keras Wolfheart]] },
        { id = 2302, name = [[Aethalas]] },
        { id = 5118, name = [[Brogun Stoneshield]] },
        { id = 5782, name = [[Crildor]] },
        { id = 11866, name = [[Ilyenia Moonfire]] },
        { id = 14378, name = [[Huntress Skymane]] },
        { id = 14379, name = [[Huntress Ravenoak]] },
        { id = 14380, name = [[Huntress Leafrunner]] },
        { id = 15709, name = [[Master Sergeant Moonshadow]] },
    },
    [1977] = {
        { id = 11338, name = [[Hakkari Shadowcaster]] },
        { id = 11339, name = [[Hakkari Shadow Hunter]] },
        { id = 11340, name = [[Hakkari Blood Priest]] },
        { id = 11347, name = [[Zealot Lor\]] },
        { id = 11348, name = [[Zealot Zath]] },
        { id = 11350, name = [[Gurubashi Axe Thrower]] },
        { id = 11351, name = [[Gurubashi Headhunter]] },
        { id = 11353, name = [[Gurubashi Blood Drinker]] },
        { id = 11356, name = [[Gurubashi Champion]] },
        { id = 11357, name = [[Son of Hakkar]] },
        { id = 11359, name = [[Soulflayer]] },
        { id = 11361, name = [[Zulian Tiger]] },
        { id = 11365, name = [[Zulian Panther]] },
        { id = 11370, name = [[Razzashi Broodwidow]] },
        { id = 11371, name = [[Razzashi Serpent]] },
        { id = 11372, name = [[Razzashi Adder]] },
        { id = 11373, name = [[Razzashi Cobra]] },
        { id = 11374, name = [[Hooktooth Frenzy]] },
        { id = 11830, name = [[Hakkari Priest]] },
        { id = 11831, name = [[Hakkari Witch Doctor]] },
        { id = 14532, name = [[Razzashi Venombrood]] },
        { id = 14750, name = [[Gurubashi Bat Rider]] },
        { id = 14821, name = [[Razzashi Raptor]] },
        { id = 14825, name = [[Withered Mistress]] },
        { id = 14882, name = [[Atal\]] },
        { id = 14883, name = [[Voodoo Slave]] },
        { id = 15042, name = [[Zanza the Restless]] },
        { id = 15043, name = [[Zulian Crocolisk]] },
        { id = 15067, name = [[Zulian Stalker]] },
        { id = 15111, name = [[Mad Servant]] },
    },
    [2017] = {
        { id = 10393, name = [[Skul]] },
        { id = 10415, name = [[Ash\]] },
        { id = 10435, name = [[Magistrate Barthilas]] },
        { id = 10436, name = [[Baroness Anastari]] },
        { id = 10437, name = [[Nerub\]] },
        { id = 10438, name = [[Maleki the Pallid]] },
        { id = 10440, name = [[Baron Rivendare]] },
        { id = 10516, name = [[The Unforgiven]] },
        { id = 10558, name = [[Hearthsinger Forresten]] },
        { id = 10809, name = [[Stonespine]] },
        { id = 10811, name = [[Archivist Galford]] },
        { id = 10812, name = [[Grand Crusader Dathrohan]] },
        { id = 10997, name = [[Cannon Master Willey]] },
        { id = 11032, name = [[Malor the Zealous]] },
        { id = 11082, name = [[Stratholme Courier]] },
        { id = 14684, name = [[Balzaphon]] },
    },
    [2057] = {
        { id = 10432, name = [[Vectus]] },
        { id = 10433, name = [[Marduk Blackpool]] },
        { id = 10502, name = [[Lady Illucia Barov]] },
        { id = 10503, name = [[Jandice Barov]] },
        { id = 10504, name = [[Lord Alexei Barov]] },
        { id = 10505, name = [[Instructor Malicia]] },
        { id = 10507, name = [[The Ravenian]] },
        { id = 10508, name = [[Ras Frostwhisper]] },
        { id = 10901, name = [[Lorekeeper Polkelt]] },
        { id = 11261, name = [[Doctor Theolen Krastinov]] },
        { id = 11622, name = [[Rattlegore]] },
        { id = 14695, name = [[Lord Blackwood]] },
        { id = 14861, name = [[Blood Steward of Kirtonos]] },
    },
    [2100] = {
        { id = 12201, name = [[Princess Theradras]] },
        { id = 12203, name = [[Landslide]] },
        { id = 12225, name = [[Celebras the Cursed]] },
        { id = 12236, name = [[Lord Vyletongue]] },
        { id = 12237, name = [[Meshlok the Harvester]] },
        { id = 12242, name = [[Spirit of Maraudos]] },
        { id = 12243, name = [[Spirit of Veng]] },
        { id = 12258, name = [[Razorlash]] },
        { id = 13282, name = [[Noxxion]] },
        { id = 13596, name = [[Rotgrip]] },
        { id = 13601, name = [[Tinkerer Gizlock]] },
    },
    [2257] = {
        { id = 5186, name = [[Basking Shark]] },
    },
    [2437] = {
        { id = 11517, name = [[Oggleflint]] },
        { id = 11518, name = [[Jergosh the Invoker]] },
        { id = 11519, name = [[Bazzalan]] },
        { id = 11520, name = [[Taragaman the Hungerer]] },
    },
    [2557] = {
        { id = 11446, name = [[Gordok Spirit]] },
        { id = 11456, name = [[Wildspawn Shadowstalker]] },
        { id = 11466, name = [[Highborne Summoner]] },
        { id = 11467, name = [[Tsu\]] },
        { id = 11487, name = [[Magister Kalendris]] },
        { id = 11488, name = [[Illyanna Ravenoak]] },
        { id = 11489, name = [[Tendris Warpwood]] },
        { id = 11490, name = [[Zevrim Thornhoof]] },
        { id = 11491, name = [[Old Ironbark]] },
        { id = 11492, name = [[Alzzin the Wildshaper]] },
        { id = 11496, name = [[Immol\]] },
        { id = 13021, name = [[Warpwood Crusher]] },
        { id = 13197, name = [[Fel Lash]] },
        { id = 13280, name = [[Hydrospawn]] },
        { id = 14308, name = [[Ferra]] },
        { id = 14321, name = [[Guard Fengus]] },
        { id = 14322, name = [[Stomper Kreeg]] },
        { id = 14323, name = [[Guard Slip\]] },
        { id = 14324, name = [[Cho\]] },
        { id = 14325, name = [[Captain Kromcrush]] },
        { id = 14326, name = [[Guard Mol\]] },
        { id = 14327, name = [[Lethtendris]] },
        { id = 14349, name = [[Pimgib]] },
        { id = 14354, name = [[Pusillin]] },
        { id = 14358, name = [[Shen\]] },
        { id = 14368, name = [[Lorekeeper Lydros]] },
        { id = 14369, name = [[Shen\]] },
        { id = 14371, name = [[Shen\]] },
        { id = 14381, name = [[Lorekeeper Javon]] },
        { id = 14382, name = [[Lorekeeper Mykos]] },
        { id = 14383, name = [[Lorekeeper Kildrath]] },
        { id = 14690, name = [[Revanchion]] },
    },
    [2597] = {
        { id = 11352, name = [[Gurubashi Berserker]] },
        { id = 11946, name = [[Drek\]] },
        { id = 11947, name = [[Captain Galvangar]] },
        { id = 11948, name = [[Vanndar Stormpike]] },
        { id = 11949, name = [[Captain Balinda Stonehearth]] },
        { id = 12121, name = [[Draka]] },
        { id = 12122, name = [[Duros]] },
        { id = 13137, name = [[Lieutenant Rugba]] },
        { id = 13138, name = [[Lieutenant Spencer]] },
        { id = 13139, name = [[Commander Randolph]] },
        { id = 13140, name = [[Commander Dardosh]] },
        { id = 13143, name = [[Lieutenant Stronghoof]] },
        { id = 13144, name = [[Lieutenant Vol\]] },
        { id = 13145, name = [[Lieutenant Grummus]] },
        { id = 13146, name = [[Lieutenant Murp]] },
        { id = 13147, name = [[Lieutenant Lewis]] },
        { id = 13151, name = [[Syndicate Master Ryson]] },
        { id = 13152, name = [[Commander Malgor]] },
        { id = 13153, name = [[Commander Mulfort]] },
        { id = 13154, name = [[Commander Louis Philips]] },
        { id = 13176, name = [[Smith Regzar]] },
        { id = 13179, name = [[Wing Commander Guse]] },
        { id = 13180, name = [[Wing Commander Jeztor]] },
        { id = 13181, name = [[Wing Commander Mulverick]] },
        { id = 13236, name = [[Primalist Thurloga]] },
        { id = 13257, name = [[Murgot Deepforge]] },
        { id = 13284, name = [[Frostwolf Shaman]] },
        { id = 13296, name = [[Lieutenant Largent]] },
        { id = 13297, name = [[Lieutenant Stouthandle]] },
        { id = 13298, name = [[Lieutenant Greywand]] },
        { id = 13299, name = [[Lieutenant Lonadin]] },
        { id = 13300, name = [[Lieutenant Mancuso]] },
        { id = 13318, name = [[Commander Mortimer]] },
        { id = 13319, name = [[Commander Duffy]] },
        { id = 13320, name = [[Commander Karl Philips]] },
        { id = 13437, name = [[Wing Commander Ichman]] },
        { id = 13438, name = [[Wing Commander Slidore]] },
        { id = 13439, name = [[Wing Commander Vipore]] },
        { id = 13441, name = [[Frostwolf Wolf Rider Commander]] },
        { id = 13442, name = [[Arch Druid Renferal]] },
        { id = 13443, name = [[Druid of the Grove]] },
        { id = 13446, name = [[Field Marshal Teravaine]] },
        { id = 13525, name = [[Seasoned Commando]] },
        { id = 13577, name = [[Stormpike Ram Rider Commander]] },
        { id = 13616, name = [[Frostwolf Stable Master]] },
        { id = 13617, name = [[Stormpike Stable Master]] },
        { id = 13959, name = [[Alterac Yeti]] },
        { id = 14762, name = [[Dun Baldar North Marshal]] },
        { id = 14763, name = [[Dun Baldar South Marshal]] },
        { id = 14764, name = [[Icewing Marshal]] },
        { id = 14765, name = [[Stonehearth Marshal]] },
        { id = 14772, name = [[East Frostwolf Warmaster]] },
        { id = 14773, name = [[Iceblood Warmaster]] },
        { id = 14776, name = [[Tower Point Warmaster]] },
        { id = 14777, name = [[West Frostwolf Warmaster]] },
    },
    [2677] = {
        { id = 12457, name = [[Blackwing Spellbinder]] },
        { id = 12458, name = [[Blackwing Taskmaster]] },
        { id = 12459, name = [[Blackwing Warlock]] },
        { id = 12460, name = [[Death Talon Wyrmguard]] },
        { id = 12461, name = [[Death Talon Overseer]] },
        { id = 12463, name = [[Death Talon Flamescale]] },
        { id = 12464, name = [[Death Talon Seether]] },
        { id = 12465, name = [[Death Talon Wyrmkin]] },
        { id = 12467, name = [[Death Talon Captain]] },
        { id = 12468, name = [[Death Talon Hatcher]] },
        { id = 12557, name = [[Grethok the Controller]] },
        { id = 13976, name = [[Tortured Drake]] },
        { id = 13996, name = [[Blackwing Technician]] },
        { id = 14401, name = [[Master Elemental Shaper Krixix]] },
        { id = 14456, name = [[Blackwing Guardsman]] },
    },
    [2717] = {
        { id = 11658, name = [[Molten Giant]] },
        { id = 11659, name = [[Molten Destroyer]] },
        { id = 11661, name = [[Flamewaker]] },
        { id = 11662, name = [[Flamewaker Priest]] },
        { id = 11671, name = [[Core Hound]] },
        { id = 11672, name = [[Core Rager]] },
        { id = 11673, name = [[Ancient Core Hound]] },
        { id = 12099, name = [[Firesworn]] },
        { id = 12119, name = [[Flamewaker Protector]] },
    },
    [3277] = {
        { id = 13116, name = [[Alliance Spirit Guide]] },
        { id = 13117, name = [[Horde Spirit Guide]] },
    },
    [3428] = {
        { id = 15229, name = [[Vekniss Soldier]] },
        { id = 15230, name = [[Vekniss Warrior]] },
        { id = 15233, name = [[Vekniss Guardian]] },
        { id = 15235, name = [[Vekniss Stinger]] },
        { id = 15236, name = [[Vekniss Wasp]] },
        { id = 15240, name = [[Vekniss Hive Crawler]] },
        { id = 15246, name = [[Qiraji Mindslayer]] },
        { id = 15247, name = [[Qiraji Brainwasher]] },
        { id = 15249, name = [[Qiraji Lasher]] },
        { id = 15250, name = [[Qiraji Slayer]] },
        { id = 15252, name = [[Qiraji Champion]] },
        { id = 15262, name = [[Obsidian Eradicator]] },
        { id = 15264, name = [[Anubisath Sentinel]] },
        { id = 15277, name = [[Anubisath Defender]] },
        { id = 15311, name = [[Anubisath Warder]] },
        { id = 15312, name = [[Obsidian Nullifier]] },
        { id = 15502, name = [[Andorgos]] },
        { id = 15503, name = [[Kandrostrasz]] },
        { id = 15504, name = [[Vethsera]] },
        { id = 15984, name = [[Sartura\]] },
    },
    [3429] = {
        { id = 15318, name = [[Hive\]] },
        { id = 15319, name = [[Hive\]] },
        { id = 15320, name = [[Hive\]] },
        { id = 15323, name = [[Hive\]] },
        { id = 15324, name = [[Qiraji Gladiator]] },
        { id = 15325, name = [[Hive\]] },
        { id = 15327, name = [[Hive\]] },
        { id = 15335, name = [[Flesh Hunter]] },
        { id = 15336, name = [[Hive\]] },
        { id = 15338, name = [[Obsidian Destroyer]] },
        { id = 15343, name = [[Qiraji Swarmguard]] },
        { id = 15344, name = [[Swarmguard Needler]] },
        { id = 15355, name = [[Anubisath Guardian]] },
        { id = 15385, name = [[Colonel Zerran]] },
        { id = 15386, name = [[Major Yeggeth]] },
        { id = 15387, name = [[Qiraji Warrior]] },
        { id = 15388, name = [[Major Pakkon]] },
        { id = 15389, name = [[Captain Drenn]] },
        { id = 15390, name = [[Captain Xurrem]] },
        { id = 15391, name = [[Captain Qeez]] },
        { id = 15392, name = [[Captain Tuubid]] },
        { id = 15461, name = [[Shrieker Scarab]] },
        { id = 15462, name = [[Spitting Scarab]] },
        { id = 15505, name = [[Canal Frenzy]] },
    },
    [3456] = {
        { id = 15974, name = [[Dread Creeper]] },
        { id = 15975, name = [[Carrion Spinner]] },
        { id = 15976, name = [[Venom Stalker]] },
        { id = 15977, name = [[Infectious Skitterer]] },
        { id = 15978, name = [[Crypt Reaver]] },
        { id = 15979, name = [[Tomb Horror]] },
        { id = 15980, name = [[Naxxramas Cultist]] },
        { id = 15981, name = [[Naxxramas Acolyte]] },
        { id = 16017, name = [[Patchwork Golem]] },
        { id = 16018, name = [[Bile Retcher]] },
        { id = 16020, name = [[Mad Scientist]] },
        { id = 16021, name = [[Living Monstrosity]] },
        { id = 16022, name = [[Surgical Assistant]] },
        { id = 16024, name = [[Embalming Slime]] },
        { id = 16025, name = [[Stitched Spewer]] },
        { id = 16029, name = [[Sludge Belcher]] },
        { id = 16034, name = [[Plague Beast]] },
        { id = 16036, name = [[Frenzied Bat]] },
        { id = 16037, name = [[Plagued Bat]] },
        { id = 16056, name = [[Diseased Maggot]] },
        { id = 16057, name = [[Rotting Maggot]] },
        { id = 16067, name = [[Skeletal Steed]] },
        { id = 16145, name = [[Deathknight Captain]] },
        { id = 16146, name = [[Deathknight]] },
        { id = 16154, name = [[Risen Deathknight]] },
        { id = 16156, name = [[Dark Touched Warrior]] },
        { id = 16157, name = [[Doom Touched Warrior]] },
        { id = 16158, name = [[Death Touched Warrior]] },
        { id = 16163, name = [[Deathknight Cavalier]] },
        { id = 16164, name = [[Shade of Naxxramas]] },
        { id = 16165, name = [[Necro Knight]] },
        { id = 16167, name = [[Bony Construct]] },
        { id = 16168, name = [[Stoneskin Gargoyle]] },
        { id = 16193, name = [[Skeletal Smith]] },
        { id = 16194, name = [[Unholy Axe]] },
        { id = 16215, name = [[Unholy Staff]] },
        { id = 16216, name = [[Unholy Swords]] },
        { id = 16236, name = [[Eye Stalk]] },
        { id = 16243, name = [[Plague Slime]] },
        { id = 16244, name = [[Infectious Ghoul]] },
        { id = 16297, name = [[Mutated Grub]] },
        { id = 16365, name = [[Master Craftsman Omarion]] },
        { id = 16368, name = [[Necropolis Acolyte]] },
        { id = 16381, name = [[Archmage Tarsis Kir-Moldir]] },
        { id = 16446, name = [[Plagued Gargoyle]] },
        { id = 16447, name = [[Plagued Ghoul]] },
        { id = 16448, name = [[Plagued Deathhound]] },
        { id = 16449, name = [[Spirit of Naxxramas]] },
        { id = 16451, name = [[Deathknight Vindicator]] },
        { id = 16452, name = [[Necro Knight Guardian]] },
        { id = 16453, name = [[Necro Stalker]] },
        { id = 16505, name = [[Naxxramas Follower]] },
        { id = 16506, name = [[Naxxramas Worshipper]] },
        { id = 16573, name = [[Crypt Guard]] },
        { id = 16803, name = [[Deathknight Understudy]] },
        { id = 16861, name = [[Death Lord]] },
    },
}
