-- DungeonRares.lua
local _, addon = ...
addon.DungeonRares = {
    [33] = {
        { id = 4275, name = [[Archmage Arugal]] },
        { id = 3887, name = [[Baron Silverlaine]] },
        { id = 4278, name = [[Commander Springvale]] },
        { id = 4274, name = [[Fenrus the Devourer]] },
        { id = 3886, name = [[Razorclaw the Butcher]] },
        { id = 3914, name = [[Rethilgore]] },
        { id = 3927, name = [[Wolf Master Nandos]] },
    },
    [34] = {
        { id = 1716, name = [[Bazil Thredd]] },
        { id = 1663, name = [[Dextren Ward]] },
        { id = 1717, name = [[Hamhock]] },
        { id = 1666, name = [[Kam Deepfury]] },
        { id = 1696, name = [[Targorr the Dread]] },
    },
    [36] = {
        { id = 647, name = [[Captain Greenskin]] },
        { id = 645, name = [[Cookie]] },
        { id = 639, name = [[Edwin VanCleef]] },
        { id = 1763, name = [[Gilnid]] },
        { id = 646, name = [[Mr. Smite]] },
        { id = 644, name = [[Rhahk'Zor]] },
    },
    [43] = {
        { id = 3653, name = [[Kresh]] },
        { id = 3669, name = [[Lord Cobrahn]] },
        { id = 3670, name = [[Lord Pythas]] },
        { id = 3673, name = [[Lord Serpentis]] },
        { id = 3674, name = [[Skum]] },
        { id = 5775, name = [[Verdan the Everliving]] },
    },
    [47] = {
        { id = 4422, name = [[Agathelos the Raging]] },
        { id = 4424, name = [[Aggem Thorncurse]] },
        { id = 4421, name = [[Charlga Razorflank]] },
        { id = 4428, name = [[Death Speaker Jargba]] },
        { id = 4420, name = [[Overlord Ramtusk]] },
        { id = 6168, name = [[Roogug]] },
    },
    [48] = {
        { id = 4829, name = [[Aku'mai]] },
        { id = 6243, name = [[Gelihast]] },
        { id = 4887, name = [[Ghamoo-ra]] },
        { id = 4831, name = [[Lady Sarevess]] },
        { id = 12902, name = [[Lorgus Jett]] },
        { id = 4830, name = [[Old Serra'kis]] },
        { id = 4832, name = [[Twilight Lord Kelris]] },
    },
    [70] = {
        { id = 7206, name = [[Ancient Stone Keeper]] },
        { id = 2748, name = [[Archaedas]] },
        { id = 6906, name = [[Baelog]] },
        { id = 7291, name = [[Galgann Firehammer]] },
        { id = 4854, name = [[Grimlok]] },
    },
    [90] = {
        { id = 6229, name = [[Crowd Pummeler 9-60]] },
        { id = 6235, name = [[Electrocutioner 6000]] },
        { id = 7800, name = [[Mekgineer Thermaplugg]] },
        { id = 7079, name = [[Viscous Fallout]] },
    },
    [109] = {
        { id = 5722, name = [[Hazzas]] },
        { id = 5710, name = [[Jammal'an the Prophet]] },
        { id = 5719, name = [[Morphaz]] },
        { id = 5709, name = [[Shade of Eranikus]] },
    },
    [129] = {
        { id = 7358, name = [[Amnennar the Coldbringer]] },
        { id = 8567, name = [[Glutton]] },
        { id = 7357, name = [[Mordresh Fire Eye]] },
    },
    [189] = {
        { id = 6487, name = [[Arcanist Doan]] },
        { id = 4543, name = [[Bloodmage Thalnos]] },
        { id = 3975, name = [[Herod]] },
        { id = 4542, name = [[High Inquisitor Fairbanks]] },
        { id = 3977, name = [[High Inquisitor Whitemane]] },
        { id = 3974, name = [[Houndmaster Loksey]] },
        { id = 3983, name = [[Interrogator Vishas]] },
    },
    [209] = {
        { id = 8127, name = [[Antu'sul]] },
        { id = 7267, name = [[Chief Ukorz Sandscalp]] },
        { id = 7795, name = [[Hydromancer Velratha]] },
        { id = 7272, name = [[Theka the Martyr]] },
        { id = 7271, name = [[Witch Doctor Zum'rah]] },
    },
    [229] = {
        { id = 10363, name = [[General Drakkisath]] },
        { id = 10220, name = [[Halycon]] },
        { id = 9196, name = [[Highlord Omokk]] },
        { id = 10596, name = [[Mother Smolderweb]] },
        { id = 9568, name = [[Overlord Wyrmthalak]] },
        { id = 9816, name = [[Pyroguard Emberseer]] },
        { id = 9736, name = [[Quartermaster Zigris]] },
        { id = 9236, name = [[Shadow Hunter Vosh'gajin]] },
        { id = 10430, name = [[The Beast]] },
        { id = 9237, name = [[War Master Voone]] },
    },
    [230] = {
        { id = 9156, name = [[Ambassador Flamelash]] },
        { id = 9035, name = [[Anger'rel]] },
        { id = 9016, name = [[Bael'Gar]] },
        { id = 9019, name = [[Emperor Dagran Thaurissan]] },
        { id = 9056, name = [[Fineous Darkvire]] },
        { id = 9033, name = [[General Angerforge]] },
        { id = 8983, name = [[Golem Lord Argelmach]] },
        { id = 9018, name = [[High Interrogator Gerstahn]] },
        { id = 9319, name = [[Houndmaster Grebmar]] },
        { id = 9017, name = [[Lord Incendius]] },
        { id = 9025, name = [[Lord Roccor]] },
        { id = 9938, name = [[Magmus]] },
        { id = 9502, name = [[Phalanx]] },
        { id = 9499, name = [[Plugger Spazzring]] },
        { id = 9024, name = [[Pyromancer Loregrain]] },
        { id = 9543, name = [[Ribbly Screwspigot]] },
        { id = 9041, name = [[Warder Stilgiss]] },
    },
    [289] = {
        { id = 11261, name = [[Doctor Theolen Krastinov]] },
        { id = 10505, name = [[Instructor Malicia]] },
        { id = 10503, name = [[Jandice Barov]] },
        { id = 10502, name = [[Lady Illucia Barov]] },
        { id = 10504, name = [[Lord Alexei Barov]] },
        { id = 10901, name = [[Lorekeeper Polkelt]] },
        { id = 10433, name = [[Marduk Blackpool]] },
        { id = 10508, name = [[Ras Frostwhisper]] },
        { id = 11622, name = [[Rattlegore]] },
        { id = 10507, name = [[The Ravenian]] },
        { id = 10432, name = [[Vectus]] },
    },
    [329] = {
        { id = 10811, name = [[Archivist Galford]] },
        { id = 10440, name = [[Baron Rivendare]] },
        { id = 10436, name = [[Baroness Anastari]] },
        { id = 10997, name = [[Cannon Master Willey]] },
        { id = 10558, name = [[Hearthsinger Forresten]] },
        { id = 10435, name = [[Magistrate Barthilas]] },
        { id = 10438, name = [[Maleki the Pallid]] },
        { id = 11032, name = [[Malor the Zealous]] },
        { id = 10437, name = [[Nerub'enkan]] },
        { id = 10516, name = [[The Unforgiven]] },
    },
    [349] = {
        { id = 12225, name = [[Celebras the Cursed]] },
        { id = 12203, name = [[Landslide]] },
        { id = 12236, name = [[Lord Vyletongue]] },
        { id = 13282, name = [[Noxxion]] },
        { id = 12201, name = [[Princess Theradras]] },
        { id = 12258, name = [[Razorlash]] },
        { id = 13596, name = [[Rotgrip]] },
        { id = 13601, name = [[Tinkerer Gizlock]] },
    },
    [389] = {
        { id = 11519, name = [[Bazzalan]] },
        { id = 11518, name = [[Jergosh the Invoker]] },
        { id = 11517, name = [[Oggleflint]] },
        { id = 11520, name = [[Taragaman the Hungerer]] },
    },
    [429] = {
        { id = 11492, name = [[Alzzin the Wildshaper]] },
        { id = 14325, name = [[Captain Kromcrush]] },
        { id = 14324, name = [[Cho'Rush the Observer]] },
        { id = 14321, name = [[Guard Fengus]] },
        { id = 14326, name = [[Guard Mol'dar]] },
        { id = 14323, name = [[Guard Slip'kik]] },
        { id = 13280, name = [[Hydrospawn]] },
        { id = 11488, name = [[Illyanna Ravenoak]] },
        { id = 11496, name = [[Immol'thar]] },
        { id = 11501, name = [[King Gordok]] },
        { id = 14327, name = [[Lethtendris]] },
        { id = 11487, name = [[Magister Kalendris]] },
        { id = 11486, name = [[Prince Tortheldrin]] },
        { id = 14322, name = [[Stomper Kreeg]] },
        { id = 11489, name = [[Tendris Warpwood]] },
        { id = 11490, name = [[Zevrim Thornhoof]] },
    },
}
